name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Detecta cambios en la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construye la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t usuario/app:latest .

      # Publica la imagen (requiere Docker Hub o un registro)
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push usuario/app:latest

      # Despliega ambos servicios en el servidor
      - name: Deploy Backend and Frontend
        run: |
          ssh user@server '
          docker pull usuario/tp5-diazmarcos-bfend-backend:latest &&
          docker pull usuario/tp5-diazmarcos-bfend-backend:latest &&
          docker-compose -f ./TP5-DiazMarcos-BFend/docker-compose.yml up -d
